"""Update models

Revision ID: 86a8f6a2b74a
Revises: bddf9c0d989b
Create Date: 2025-10-13 17:25:54.652573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a8f6a2b74a'
down_revision: Union[str, Sequence[str], None] = 'bddf9c0d989b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema by dropping and recreating the table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_note')
    op.create_table('tbl_note',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('content', sa.String(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['tbl_user.id'], name='fk_note_user'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema by dropping and recreating the table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_note')
    op.create_table('tbl_note',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('body', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###