"""Create notes

Revision ID: 217566872bfa
Revises: d508137d14ee
Create Date: 2025-09-09 13:35:37.410933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '217566872bfa'
down_revision: Union[str, Sequence[str], None] = 'd508137d14ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_note_history',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['tbl_note.id'], ),
    sa.PrimaryKeyConstraint('note_id', 'update_at')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_note_history')
    op.drop_table('tbl_note')
    # ### end Alembic commands ###
